title: "Personal Portfolio"
name: "Trần Khôi Nguyên"
description: "IoT Research and Engineering"
url: "https://khoinguyen0110.github.io"
bio: "Engineering Student at PTIT | IoT enthusiast."
location: "Thanh Pho Ho Chi Minh, Vietnam"
email: "khoinguyen0110@gmail.com"
github: "khoinguyen0110"